// Turns a reviewed plan into (1) the minimal set of move/create actions needed
// to actually reorganize the drive, and (2) a full old-path -> new-path log for
// every source folder, for "this used to be here, where is it now?" lookups.
// Pure functions over a store -- no DOM here (buildSearchLogHtml returns a
// *string* of HTML for someone else to download, it doesn't touch document).
//
// Why the action list is so much smaller than "every folder": store.js only
// ever records an override on a folder when it's individually renamed / moved /
// trashed / detached (see setOverride's no-op normalisation). A folder with no
// override of its own automatically inherits wherever its nearest overridden
// ancestor ends up, because destPath()/effParentKey() walk that chain live. So
// "folders needing their own explicit command" is exactly
// { id : folderStatus(id) !== "unchanged" } -- already minimal by construction,
// no separate subtree-analysis pass required.

// Commands must run deepest-source-folder-first: if a folder F needs its own
// move AND some descendant D also needs its own (possibly unrelated) move, D
// has to be extracted before F's bulk recursive move runs, or D would get
// silently swept along to F's destination. Sorting the whole action list by
// source depth, descending, gives a single global order where every folder is
// always processed before any of its real-disk ancestors move -- regardless of
// which branch it's in.
export function computeMovePlan(store) {
  const moves = [];
  const trashed = [];
  const pendingUnresolved = [];

  for (const id of store.sourceIds()) {
    const status = store.folderStatus(id);
    if (status === "unchanged") continue;
    const from = store.srcPath(id);
    if (status === "deleted") {
      trashed.push({ id, from, status });
    } else if (status === "pending") {
      pendingUnresolved.push({ id, from, status });
    } else {
      const depth = store.srcAncestorChain(id).length;
      moves.push({ id, from, to: store.destPath(id), status, depth });
    }
  }
  moves.sort((a, b) => b.depth - a.depth);

  // Brand-new (skeleton or hand-created) folders that survived review and have
  // nothing moved into them yet. Only leaves need an explicit mkdir -- Windows
  // md/mkdir creates intermediate directories automatically, and any folder
  // that DOES have children will already get created as a side effect of
  // whichever move/mkdir command targets those children.
  const newFolders = [];
  for (const id of store.allIds()) {
    if (id === store.TRASH || id === store.PENDING || !store.isNew(id)) continue;
    if (store.folderStatus(id) !== "new") continue;
    if (store.getDestChildren(id).length > 0) continue;
    newFolders.push({ id, path: store.destPath(id) });
  }

  return { moves, trashed, pendingUnresolved, newFolders, sourceRoot: store.sourceRoot };
}

// Every source folder's old path, its computed new path (null if trashed/
// pending -- neither is a real destination), and its status. This is the
// comprehensive, unoptimized list the searchable log is built from.
export function computeFullLog(store) {
  const rows = [];
  for (const id of store.sourceIds()) {
    const status = store.folderStatus(id);
    const oldPath = store.srcPath(id);
    const newPath = status === "deleted" || status === "pending" ? null : store.destPath(id);
    rows.push({ oldPath, newPath, status });
  }
  rows.sort((a, b) => (a.oldPath < b.oldPath ? -1 : a.oldPath > b.oldPath ? 1 : 0));
  return rows;
}

function batchQuote(path) {
  return `"${path}"`;
}

// A .bat script, not an already-approved action: it gates itself behind a
// typed confirmation, logs every robocopy call, and collects failures into a
// separate errors file instead of stopping the whole run on the first one.
// Trashed/pending folders are deliberately NOT turned into delete commands --
// see the header comment for why (deletion is irreversible; that step is left
// for a human to run deliberately after reviewing the flagged list).
export function buildRobocopyScript(plan, { generatedAt = new Date() } = {}) {
  const lines = [];
  lines.push("@echo off");
  lines.push("setlocal enabledelayedexpansion");
  lines.push("rem Generated by Folder Migration Planner on " + generatedAt.toISOString());
  lines.push("rem Source root: " + plan.sourceRoot);
  lines.push("rem");
  lines.push(`rem ${plan.newFolders.length} folder(s) to create, ${plan.moves.length} folder(s) to move.`);
  lines.push(
    `rem ${plan.trashed.length} folder(s) are flagged for deletion and ${plan.pendingUnresolved.length} are still`
  );
  lines.push("rem unresolved (Pending) -- neither is acted on here. See the searchable log for those lists.");
  lines.push("rem");
  lines.push("rem /MOVE deletes each source folder once its contents are safely copied -- this script makes");
  lines.push("rem real, mostly-irreversible changes to the drive. Consider a dry run first: change ROBO_OPTS");
  lines.push("rem below to add /L (list only, copies/moves/deletes nothing) and re-run to preview.");
  lines.push("rem To preserve NTFS permissions/ownership during the move, consider adding /SEC or /COPYALL.");
  lines.push("");
  lines.push('set "ROBO_OPTS=/E /MOVE /R:2 /W:5 /MT:8 /NFL /NDL /NP"');
  lines.push('set "LOGFILE=%~dp0migration-log.txt"');
  lines.push('set "ERRFILE=%~dp0migration-errors.txt"');
  lines.push("set ERRCOUNT=0");
  lines.push("");
  lines.push("echo This will MOVE folders on the drive according to the reviewed plan.");
  lines.push('echo A full robocopy log will be written to "%LOGFILE%".');
  lines.push("echo.");
  lines.push("set /p CONFIRM=Type YES to proceed: ");
  lines.push('if /I not "%CONFIRM%"=="YES" (');
  lines.push("  echo Cancelled.");
  lines.push("  exit /b 1");
  lines.push(")");
  lines.push("");
  lines.push('if exist "%ERRFILE%" del "%ERRFILE%"');
  lines.push("");

  if (plan.newFolders.length) {
    lines.push("rem --- new folders (no content to move yet) ---");
    for (const nf of plan.newFolders) {
      const p = batchQuote(nf.path);
      lines.push(`if not exist ${p} mkdir ${p}`);
    }
    lines.push("");
  }

  if (plan.moves.length) {
    lines.push("rem --- moves, deepest source folder first (see export.js for why) ---");
    for (const m of plan.moves) {
      lines.push(`call :MOVE ${batchQuote(m.from)} ${batchQuote(m.to)}`);
    }
    lines.push("");
  }

  lines.push("echo.");
  lines.push("if %ERRCOUNT% GTR 0 (");
  lines.push('  echo %ERRCOUNT% move^(s^) reported errors -- see "%ERRFILE%" and "%LOGFILE%"');
  lines.push(") else (");
  lines.push("  echo All moves completed with no errors reported.");
  lines.push(")");
  lines.push("pause");
  lines.push("exit /b 0");
  lines.push("");
  lines.push(":MOVE");
  lines.push('robocopy "%~1" "%~2" %ROBO_OPTS% /LOG+:"%LOGFILE%"');
  lines.push("if errorlevel 8 (");
  lines.push("  set /a ERRCOUNT+=1");
  lines.push('  echo FAILED: "%~1" -^> "%~2" >> "%ERRFILE%"');
  lines.push(")");
  lines.push("exit /b 0");
  lines.push("");
  return lines.join("\r\n");
}

const STATUS_LABEL = {
  unchanged: "unchanged",
  moved: "moved",
  renamed: "renamed",
  "moved+renamed": "moved & renamed",
  deleted: "flagged for deletion (not moved)",
  pending: "pending review (no destination chosen yet)",
};

function csvField(value) {
  const s = value ?? "";
  return /[",\r\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

export function buildSearchLogCsv(rows) {
  const lines = ["Old Path,New Path,Status"];
  for (const r of rows) {
    lines.push(
      [csvField(r.oldPath), csvField(r.newPath ?? ""), csvField(STATUS_LABEL[r.status] ?? r.status)].join(",")
    );
  }
  return lines.join("\r\n");
}

// A single, dependency-free HTML file: works offline from file:// like the
// rest of this tool, no server or build step needed to open it. The common
// sourceRoot prefix is stripped from every path before embedding (cuts file
// size meaningfully at ~100k rows) and re-added once in the header + at render
// time. Filtering is a plain Array.filter over an in-memory array (not the
// DOM), so it stays fast even at full scale; only the first MATCH_LIMIT
// results are ever rendered to keep the page itself responsive.
export function buildSearchLogHtml(rows, { sourceRoot, generatedAt = new Date() } = {}) {
  const prefix = sourceRoot ? sourceRoot + "\\" : "";
  const stripped = rows.map((r) => [
    r.oldPath.startsWith(prefix) ? r.oldPath.slice(prefix.length) : r.oldPath,
    r.newPath == null ? null : r.newPath.startsWith(prefix) ? r.newPath.slice(prefix.length) : r.newPath,
    STATUS_LABEL[r.status] ?? r.status,
  ]);
  const dataJson = JSON.stringify(stripped).replace(/</g, "\\u003c");
  const rootJson = JSON.stringify(sourceRoot ?? "").replace(/</g, "\\u003c");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Folder migration log</title>
<style>
  body { font-family: system-ui, sans-serif; margin: 0; padding: 16px 24px 40px; background: #fafafa; color: #222; }
  h1 { font-size: 18px; margin: 0 0 4px; }
  .meta { color: #666; font-size: 13px; margin-bottom: 14px; }
  #q { width: 100%; max-width: 640px; padding: 8px 10px; font-size: 15px; box-sizing: border-box; }
  #count { margin: 10px 0; font-size: 13px; color: #555; }
  table { border-collapse: collapse; width: 100%; font-size: 13px; background: #fff; }
  th, td { text-align: left; padding: 5px 10px; border-bottom: 1px solid #eee; vertical-align: top; }
  th { position: sticky; top: 0; background: #fff; border-bottom: 2px solid #ccc; }
  td.path { font-family: Consolas, monospace; word-break: break-all; }
  td.status-deleted { color: #a33; }
  td.status-pending { color: #b8860b; }
  mark { background: #ffe58a; padding: 0; }
</style>
</head>
<body>
<h1>Folder migration log</h1>
<div class="meta">Generated ${generatedAt.toISOString()} &middot; root: <code id="root"></code> &middot; ${
    stripped.length
  } folders</div>
<input id="q" type="text" placeholder="Search an old or new path or folder name…" autofocus />
<div id="count"></div>
<table>
  <thead><tr><th style="width:38%">Old Path</th><th style="width:38%">New Path</th><th>Status</th></tr></thead>
  <tbody id="rows"></tbody>
</table>
<script>
  var ROOT = ${rootJson};
  var DATA = ${dataJson}; // [oldPathRelative, newPathRelative|null, statusLabel][]
  var MATCH_LIMIT = 300;
  document.getElementById("root").textContent = ROOT || "(unknown)";

  function esc(s) {
    return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  }
  function full(rel) {
    return rel == null ? "(none)" : ROOT ? ROOT + "\\\\" + rel : rel;
  }
  function highlight(text, needle) {
    if (!needle) return esc(text);
    var i = text.toLowerCase().indexOf(needle);
    if (i === -1) return esc(text);
    return esc(text.slice(0, i)) + "<mark>" + esc(text.slice(i, i + needle.length)) + "</mark>" + esc(text.slice(i + needle.length));
  }

  var qEl = document.getElementById("q");
  var countEl = document.getElementById("count");
  var rowsEl = document.getElementById("rows");
  var timer = null;

  function render() {
    var needle = qEl.value.trim().toLowerCase();
    var matches = [];
    for (var i = 0; i < DATA.length && matches.length <= MATCH_LIMIT; i++) {
      var row = DATA[i];
      if (!needle || row[0].toLowerCase().indexOf(needle) !== -1 || (row[1] && row[1].toLowerCase().indexOf(needle) !== -1)) {
        matches.push(row);
      }
    }
    var truncated = matches.length > MATCH_LIMIT;
    if (truncated) matches.length = MATCH_LIMIT;
    countEl.textContent = needle
      ? (truncated ? "Showing first " + MATCH_LIMIT + " matches -- refine your search to narrow it down." : matches.length + " match" + (matches.length === 1 ? "" : "es"))
      : "Showing first " + matches.length + " of " + DATA.length + " folders -- type to search.";
    var html = "";
    for (var j = 0; j < matches.length; j++) {
      var r = matches[j];
      var oldFull = full(r[0]);
      var newFull = full(r[1]);
      var statusClass = r[2].indexOf("deletion") !== -1 ? "status-deleted" : r[2].indexOf("pending") !== -1 ? "status-pending" : "";
      html += "<tr><td class=\\"path\\">" + highlight(oldFull, needle) + "</td><td class=\\"path\\">" + highlight(newFull, needle) + "</td><td class=\\"" + statusClass + "\\">" + esc(r[2]) + "</td></tr>";
    }
    rowsEl.innerHTML = html;
  }

  qEl.addEventListener("input", function () {
    clearTimeout(timer);
    timer = setTimeout(render, 120);
  });
  render();
</script>
</body>
</html>
`;
}
